invited_reviewer:
  - "UbiComp / ISWC · UbiSense 2025"
  - "IEEE Internet of Things Journal"
  - "IEEE Transactions on Mobile Computing"
  - "IEEE Internet Computing"
  - "HAI 2025 - Poster track"

invited_pc:
  - "IEEE DSAA 2025"